# Generated by Django 3.0.5 on 2023-01-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=100)),
                ('e_q_num', models.IntegerField()),
                ('e_marks', models.IntegerField()),
                ('t_id', models.CharField(max_length=10)),
            ],
        ),
    ]
