# Generated by Django 3.0.5 on 2023-01-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='e_id',
            field=models.CharField(default='ok', max_length=10),
            preserve_default=False,
        ),
    ]
