# Generated by Django 3.0.5 on 2023-01-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam_e_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='b_id',
            field=models.CharField(default='h', max_length=10),
            preserve_default=False,
        ),
    ]
