# Generated by Django 3.0.5 on 2023-01-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_exam_b_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='e_time',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
    ]
