# Generated by Django 3.0.5 on 2023-01-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_exam_e_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='e_time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='exam',
            name='st_time',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
    ]
