# Generated by Django 4.1.7 on 2023-03-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_exam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='b_name',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
    ]
