# Generated by Django 3.0.5 on 2023-01-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='t_is_logged_in',
            field=models.CharField(default='FALSE', max_length=5),
        ),
    ]
