# Generated by Django 3.0.5 on 2023-01-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20230122_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='t_pfp',
            field=models.ImageField(default='Default_pfp.png', upload_to='t_pfps'),
        ),
    ]
