# Generated by Django 3.0.5 on 2023-02-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_teacher_t_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='t_remember',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
    ]
