# Generated by Django 4.1.7 on 2023-03-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='ha_id',
            field=models.CharField(default='8954921878', max_length=10),
            preserve_default=False,
        ),
    ]
