# Generated by Django 4.1.7 on 2023-03-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadAdmin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('h_id', models.CharField(max_length=10)),
                ('h_name', models.CharField(max_length=50)),
                ('h_email', models.CharField(max_length=100)),
                ('h_password', models.CharField(max_length=100)),
                ('h_pfp', models.ImageField(default='Default_pfp.png', upload_to='t_pfps')),
                ('h_is_logged_in', models.CharField(max_length=255)),
                ('h_remember', models.CharField(max_length=255)),
            ],
        ),
    ]
