# Generated by Django 3.0.5 on 2023-01-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='b_name',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
