# Generated by Django 3.0.5 on 2023-01-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_text', models.CharField(max_length=255)),
                ('op_a', models.CharField(max_length=255)),
                ('op_b', models.CharField(max_length=255)),
                ('op_c', models.CharField(max_length=255)),
                ('op_d', models.CharField(max_length=255)),
                ('ans', models.CharField(max_length=255)),
                ('b_id', models.CharField(max_length=10)),
            ],
        ),
    ]
