# Generated by Django 3.0.5 on 2023-01-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_s_is_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_is_logged_in',
            field=models.CharField(max_length=255),
        ),
    ]
