# Generated by Django 3.0.5 on 2023-01-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20230122_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_pfp',
            field=models.ImageField(default='Default_pfp.svg.png', upload_to='s_pfps'),
        ),
    ]
