# Generated by Django 3.0.5 on 2023-01-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.CharField(max_length=10)),
                ('notify_text', models.CharField(max_length=255)),
                ('notify_time', models.CharField(max_length=255)),
            ],
        ),
    ]
